sonar.sources=.
sonar.test.inclusions=**/*_test.go
sonar.go.coverage.reportPaths=coverage/coverage.out
sonar.exclusions=**/node_modules/**,dist/**,coverage/**,.scannerwork/**,**/.env*,.next/**,.pi/**,build/**,out/**,.turbo/**,.vercel/**
