// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package postgres

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type ForgotPasswordEmail struct {
	ID        pgtype.UUID
	UserID    int32
	Email     string
	ExpiredAt pgtype.Timestamp
	CreatedAt pgtype.Timestamp
}

type RefreshToken struct {
	ID        pgtype.UUID
	UserID    int32
	TokenHash []byte
	FamilyID  pgtype.UUID
	ParentID  pgtype.UUID
	ExpiredAt pgtype.Timestamp
	UsedAt    pgtype.Timestamp
	RevokedAt pgtype.Timestamp
	CreatedAt pgtype.Timestamp
	IpAddress string
	UserAgent string
}

type User struct {
	ID         int32
	OauthID    pgtype.Text
	Username   string
	AvatarUrl  pgtype.Text
	Email      string
	Password   string
	IsVerified pgtype.Bool
	Provider   pgtype.Text
	CreatedAt  pgtype.Timestamp
	UpdatedAt  pgtype.Timestamp
}

type VerifyEmail struct {
	ID        pgtype.UUID
	UserID    int32
	Email     string
	ExpiredAt pgtype.Timestamp
	CreatedAt pgtype.Timestamp
}
