// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package postgres

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createForgotPasswordEmail = `-- name: CreateForgotPasswordEmail :exec
INSERT INTO forgot_password_emails (id, user_id, email, expired_at)
VALUES ($1, $2, $3, $4)
`

type CreateForgotPasswordEmailParams struct {
	ID        pgtype.UUID
	UserID    int32
	Email     string
	ExpiredAt pgtype.Timestamp
}

func (q *Queries) CreateForgotPasswordEmail(ctx context.Context, arg CreateForgotPasswordEmailParams) error {
	_, err := q.db.Exec(ctx, createForgotPasswordEmail,
		arg.ID,
		arg.UserID,
		arg.Email,
		arg.ExpiredAt,
	)
	return err
}

const createRefreshToken = `-- name: CreateRefreshToken :exec
INSERT INTO refresh_tokens (id, user_id, token_hash, family_id, parent_id, expired_at, created_at, ip_address, user_agent)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
`

type CreateRefreshTokenParams struct {
	ID        pgtype.UUID
	UserID    int32
	TokenHash []byte
	FamilyID  pgtype.UUID
	ParentID  pgtype.UUID
	ExpiredAt pgtype.Timestamp
	CreatedAt pgtype.Timestamp
	IpAddress string
	UserAgent string
}

func (q *Queries) CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) error {
	_, err := q.db.Exec(ctx, createRefreshToken,
		arg.ID,
		arg.UserID,
		arg.TokenHash,
		arg.FamilyID,
		arg.ParentID,
		arg.ExpiredAt,
		arg.CreatedAt,
		arg.IpAddress,
		arg.UserAgent,
	)
	return err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (username, email, password)
VALUES ($1, $2, $3)
RETURNING users.id
`

type CreateUserParams struct {
	Username string
	Email    string
	Password string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (int32, error) {
	row := q.db.QueryRow(ctx, createUser, arg.Username, arg.Email, arg.Password)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const createVerifyEmail = `-- name: CreateVerifyEmail :exec
INSERT INTO verify_emails (id, user_id, email, expired_at)
VALUES ($1, $2, $3, $4)
`

type CreateVerifyEmailParams struct {
	ID        pgtype.UUID
	UserID    int32
	Email     string
	ExpiredAt pgtype.Timestamp
}

func (q *Queries) CreateVerifyEmail(ctx context.Context, arg CreateVerifyEmailParams) error {
	_, err := q.db.Exec(ctx, createVerifyEmail,
		arg.ID,
		arg.UserID,
		arg.Email,
		arg.ExpiredAt,
	)
	return err
}

const deleteForgotPasswordByID = `-- name: DeleteForgotPasswordByID :exec
DELETE FROM forgot_password_emails
WHERE forgot_password_emails.id = $1
`

func (q *Queries) DeleteForgotPasswordByID(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteForgotPasswordByID, id)
	return err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users
WHERE users.id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteUser, id)
	return err
}

const getAllUsers = `-- name: GetAllUsers :many
SELECT users.id, users.username, users.email, users.is_verified, users.updated_at, users.created_at
FROM users
ORDER BY users.id
`

type GetAllUsersRow struct {
	ID         int32
	Username   string
	Email      string
	IsVerified pgtype.Bool
	UpdatedAt  pgtype.Timestamp
	CreatedAt  pgtype.Timestamp
}

func (q *Queries) GetAllUsers(ctx context.Context) ([]GetAllUsersRow, error) {
	rows, err := q.db.Query(ctx, getAllUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllUsersRow
	for rows.Next() {
		var i GetAllUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.Email,
			&i.IsVerified,
			&i.UpdatedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getForgotPasswordByID = `-- name: GetForgotPasswordByID :one
SELECT forgot_password_emails.id, forgot_password_emails.user_id, forgot_password_emails.email, forgot_password_emails.expired_at
FROM forgot_password_emails
WHERE forgot_password_emails.id = $1
`

type GetForgotPasswordByIDRow struct {
	ID        pgtype.UUID
	UserID    int32
	Email     string
	ExpiredAt pgtype.Timestamp
}

func (q *Queries) GetForgotPasswordByID(ctx context.Context, id pgtype.UUID) (GetForgotPasswordByIDRow, error) {
	row := q.db.QueryRow(ctx, getForgotPasswordByID, id)
	var i GetForgotPasswordByIDRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Email,
		&i.ExpiredAt,
	)
	return i, err
}

const getRefreshTokenByHash = `-- name: GetRefreshTokenByHash :one
SELECT id, user_id, token_hash, family_id, parent_id, expired_at, used_at, revoked_at, created_at, ip_address, user_agent
FROM refresh_tokens
WHERE token_hash = $1
FOR UPDATE
`

func (q *Queries) GetRefreshTokenByHash(ctx context.Context, tokenHash []byte) (RefreshToken, error) {
	row := q.db.QueryRow(ctx, getRefreshTokenByHash, tokenHash)
	var i RefreshToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.FamilyID,
		&i.ParentID,
		&i.ExpiredAt,
		&i.UsedAt,
		&i.RevokedAt,
		&i.CreatedAt,
		&i.IpAddress,
		&i.UserAgent,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT users.id, users.username, users.email, users.is_verified, users.password, users.updated_at, users.created_at
FROM users
WHERE users.email = $1
`

type GetUserByEmailRow struct {
	ID         int32
	Username   string
	Email      string
	IsVerified pgtype.Bool
	Password   string
	UpdatedAt  pgtype.Timestamp
	CreatedAt  pgtype.Timestamp
}

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (GetUserByEmailRow, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i GetUserByEmailRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.IsVerified,
		&i.Password,
		&i.UpdatedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByEmailWithoutPassword = `-- name: GetUserByEmailWithoutPassword :one
SELECT users.id, users.username, users.email, users.is_verified, users.updated_at, users.created_at
FROM users
WHERE users.email = $1
`

type GetUserByEmailWithoutPasswordRow struct {
	ID         int32
	Username   string
	Email      string
	IsVerified pgtype.Bool
	UpdatedAt  pgtype.Timestamp
	CreatedAt  pgtype.Timestamp
}

func (q *Queries) GetUserByEmailWithoutPassword(ctx context.Context, email string) (GetUserByEmailWithoutPasswordRow, error) {
	row := q.db.QueryRow(ctx, getUserByEmailWithoutPassword, email)
	var i GetUserByEmailWithoutPasswordRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.IsVerified,
		&i.UpdatedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT users.id, users.username, users.email, users.is_verified, users.updated_at, users.created_at
FROM users
WHERE users.id = $1
`

type GetUserByIDRow struct {
	ID         int32
	Username   string
	Email      string
	IsVerified pgtype.Bool
	UpdatedAt  pgtype.Timestamp
	CreatedAt  pgtype.Timestamp
}

func (q *Queries) GetUserByID(ctx context.Context, id int32) (GetUserByIDRow, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i GetUserByIDRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.IsVerified,
		&i.UpdatedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getVerifyEmailByID = `-- name: GetVerifyEmailByID :one
SELECT verify_emails.id, verify_emails.email, verify_emails.expired_at
FROM verify_emails
WHERE verify_emails.id = $1
`

type GetVerifyEmailByIDRow struct {
	ID        pgtype.UUID
	Email     string
	ExpiredAt pgtype.Timestamp
}

func (q *Queries) GetVerifyEmailByID(ctx context.Context, id pgtype.UUID) (GetVerifyEmailByIDRow, error) {
	row := q.db.QueryRow(ctx, getVerifyEmailByID, id)
	var i GetVerifyEmailByIDRow
	err := row.Scan(&i.ID, &i.Email, &i.ExpiredAt)
	return i, err
}

const revokeRefreshToken = `-- name: RevokeRefreshToken :exec
UPDATE refresh_tokens
SET revoked_at = NOW()
WHERE id = $1
`

func (q *Queries) RevokeRefreshToken(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, revokeRefreshToken, id)
	return err
}

const revokeRefreshTokenFamily = `-- name: RevokeRefreshTokenFamily :exec
UPDATE refresh_tokens
SET revoked_at = NOW()
WHERE family_id = $1 AND revoked_at IS NULL
`

func (q *Queries) RevokeRefreshTokenFamily(ctx context.Context, familyID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, revokeRefreshTokenFamily, familyID)
	return err
}

const updateUser = `-- name: UpdateUser :exec
UPDATE users
SET username = $1, email = $2
WHERE users.id = $3
`

type UpdateUserParams struct {
	Username string
	Email    string
	ID       int32
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) error {
	_, err := q.db.Exec(ctx, updateUser, arg.Username, arg.Email, arg.ID)
	return err
}

const updateUserPassword = `-- name: UpdateUserPassword :exec
UPDATE users
SET password = $1
WHERE users.id = $2
`

type UpdateUserPasswordParams struct {
	Password string
	ID       int32
}

func (q *Queries) UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error {
	_, err := q.db.Exec(ctx, updateUserPassword, arg.Password, arg.ID)
	return err
}

const useRefreshToken = `-- name: UseRefreshToken :exec
UPDATE refresh_tokens
SET used_at = NOW()
WHERE id = $1 AND used_at IS NULL
`

func (q *Queries) UseRefreshToken(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, useRefreshToken, id)
	return err
}

const verifyEmailByToken = `-- name: VerifyEmailByToken :exec
UPDATE users
SET is_verified = true
WHERE users.email = (SELECT verify_emails.email FROM verify_emails WHERE verify_emails.id = $1)
`

func (q *Queries) VerifyEmailByToken(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, verifyEmailByToken, id)
	return err
}

const verifyEmailDeleteToken = `-- name: VerifyEmailDeleteToken :exec
DELETE FROM verify_emails
WHERE verify_emails.id = $1
`

func (q *Queries) VerifyEmailDeleteToken(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, verifyEmailDeleteToken, id)
	return err
}
